export const ORDER_COLUMNS = [
  "ID",
  "Name",
  "Email",
  "Date",
  "Customer",
  "Channel",
  "Total",
  "Subtotal",
  "Taxes",
  "Discounts",
  "Discount Code",
  "Payment status",
  "Fulfillment status",
  "Delivery status",
  "Delivery method",
  "Shipping Cost",
  "Tags",
  "Destination",
  "Billing Name",
  "Billing Address1",
  "Billing Address2",
  "Billing City",
  "Billing Zip",
  "Billing Province",
  "Billing Country",
  "Billing Phone",
  "Shipping Name",
  "Shipping Address1",
  "Shipping Address2",
  "Shipping Company",
  "Shipping City",
  "Shipping Zip",
  "Shipping Province",
  "Shipping Country",
  "Shipping Phone",
  "Cancelled At",
  "Cancel Reason",
  "Return status",
  "PO number",
  "Note",
  "Customer: Email",
  "Command",
  "Line: SKU",
  "Line: Quantity",
  "Line: Price",
  "Line: Title",
  "Line: Vendor",
  "Line: Taxable",
  "Line: Command",
];

export const EXPORT_ONLY_COLUMNS = [
  "Payment status", 
  "Fulfillment status", 
  "Delivery status", 
  "Delivery method", 
  "Return status", 
  "PO number", 
  "Subtotal", 
  "Taxes", 
  "Discounts", 
  "Discount Code", 
  "Shipping Cost", 
  "Billing Name", 
  "Billing Address1", 
  "Billing Address2", 
  "Billing City", 
  "Billing Zip", 
  "Billing Province", 
  "Billing Country", 
  "Billing Phone", 
  "Shipping Name", 
  "Shipping Address1", 
  "Shipping Address2", 
  "Shipping Company", 
  "Shipping City", 
  "Shipping Zip", 
  "Shipping Province", 
  "Shipping Country", 
  "Shipping Phone", 
  "Cancelled At", 
  "Cancel Reason",
  "Line: Vendor",
  "Line: Taxable"
];
